In [1]:
import pandas as pd

df = pd.read_excel('data/2024people.xlsx',skiprows=2,index_col='행정기관',usecols='A:B,C:F',nrows=2)

c:\python3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [11]:
df = pd.read_excel('data/2024people_age.xlsx',skiprows=3,usecols='B:C,E:O',index_col='행정기관',nrows=1)

c:\python3\Lib\site-packages\openpyxl\styles\stylesheet.py:237: UserWarning: Workbook contains no default style, apply openpyxl's default
  warn("Workbook contains no default style, apply openpyxl's default")

In [13]:
df = pd.read_excel('data/score.xlsx',index_col='지원번호')

In [ ]:
# 컬럼 부분 출력하기 
df['키']
df['이름']

df.columns  # == ['이름','학교','키','국어','영어','수학','과학','사회','SW특기']
df.columns[0]   # == '이름'
df[df.columns[0]] # == df['이름']

# 컬럼 2개 이상 출력 (대괄호 두 개만 가능)
df[['키','이름']]
df[['이름','학교','SW특기']]
df[df.columns[1:6]]     # df.columns 리스트를 슬라이싱해서 사용
df[df.columns[:-1]]     # 가장 끝 컬럼 제외
# df[1:6] # row 출력
df[df.columns[[1,3,4]]] # 컬럼 지정 출력


# 그냥 있는 슬라이싱은 row에 대응됨
df[df.columns[5:]][1:3]

        학교   국어   영어
지원번호
1번     가산고   90   85
2번     가산고   40   35
3번     가산고   80   75
4번     가산고   40   60
5번     가산고   15   20
6번    디지털고   80  100
7번    디지털고   55   65
8번    디지털고  100   85

In [33]:
df

       이름    학교    키   국어   영어   수학  과학  사회        SW특기
지원번호
1번    홍길동   가산고  197   90   85  100  95  85      Python
2번    유관순   가산고  184   40   35   50  55  25        Java
3번    이순신   가산고  168   80   75   70  80  75  Javascript
4번    강감찬   가산고  187   40   60   70  75  80         NaN
5번     김구   가산고  188   15   20   10  35  10         NaN
6번    김유신  디지털고  202   80  100   95  85  80           C
7번    홍길자  디지털고  188   55   65   45  40  35      PYTHON
8번    홍길순  디지털고  190  100   85   90  95  95          C#